language: go

go:
  - "1.3"
  - "1.4"
  - "1.5"
  - "1.6"
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - tip

install:
  - make get-deps

script:
  - ./test.sh

matrix:
  include:
    - go: "1.3"
      env: NOCONTEXT=1
    - go: "1.4"
      env: NOCONTEXT=1
    - go: "1.5"
      env: NOCONTEXT=1
    - go: "1.6"
      env: NOCONTEXT=1

after_success:
  - bash <(curl -s https://codecov.io/bash)
